name: Lint, Format, and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checks:
    name: Linters and Tests
    runs-on: ubuntu-latest
    env:
      R_LIBS_USER: ${{ github.workspace }}/.r-lib
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          # Use Posit's Public Package Manager mirror for faster installs
          use-public-rspm: true
      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::lintr
            any::styler
            any::devtools
          needs: check
          cache-version: 1
      - name: Run lintr
        run: >-
          Rscript --vanilla scripts/precommit_lintr.R $(git ls-files -- '*.R' '*.r' '*.Rmd' '*.rmd')
        shell: bash
      - name: Run styler (check formatting)
        run: >-
          Rscript --vanilla scripts/precommit_styler.R $(git ls-files -- '*.R' '*.r' '*.Rmd' '*.rmd') &&
          git diff --exit-code
        shell: bash
      - name: Run testthat suite
        run: >-
          R -q -e "devtools::test(stop_on_failure = TRUE, stop_on_warning = FALSE)"
